trip_plan_task:
  description: >
    Develop a **comprehensive and structured** itinerary from {travel_start_Date} to {travel_end_Date}, ensuring:
    - **Arrival logistics**: Airport transfer from {destination_airport} to {destination_location}.
    - **Day-wise schedule** covering:
      - **Activities from {place_selection_modified_op}** with time-stamped details.
      - **Dining recommendations** based on {food_preferences}.
      - **Hotel check-in/out details** for {hotel_accomodation_type}.
      - **Realistic travel durations & mode of transport** (taxi, bus, rental, etc.).
      - **Cost estimates for each activity, meal, transport, and stay**.
      - **Alternative recommendations in case of weather or schedule changes**.
    - **Departure logistics**: Flight {return_flight}, airport transfer.

  expected_output: >
    - **A fully structured itinerary** covering arrival, day-wise plans, and departure.
    - **Estimated costs per activity, transport, and accommodation**.
    - **Realistic logistics for seamless transitions between activities**.
    - **Total trip cost breakdown per person**.
  agent: trip_planner

